/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/app${'/(landing)'}/layout` | `/../../web/app/layout`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/landing/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/landing/hero`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/landing/features`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/landing/stats`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/landing/final-cta`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/landing/footer`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/layouts/header/app-header`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/index.test`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/app${'/(landing)'}/layout` | `/../../web/app/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/components/landing/navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/components/landing/hero`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/components/landing/features`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/components/landing/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/components/landing/final-cta`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/components/landing/footer`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/components/layouts/header/app-header`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/index.test`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/../../web/app${'/(landing)'}/layout${`?${string}` | `#${string}` | ''}` | `/../../web/app/layout${`?${string}` | `#${string}` | ''}` | `/../../web/components/landing/navigation${`?${string}` | `#${string}` | ''}` | `/../../web/components/landing/hero${`?${string}` | `#${string}` | ''}` | `/../../web/components/landing/features${`?${string}` | `#${string}` | ''}` | `/../../web/components/landing/stats${`?${string}` | `#${string}` | ''}` | `/../../web/components/landing/final-cta${`?${string}` | `#${string}` | ''}` | `/../../web/components/landing/footer${`?${string}` | `#${string}` | ''}` | `/../../web/components/layouts/header/app-header${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/two${`?${string}` | `#${string}` | ''}` | `/two${`?${string}` | `#${string}` | ''}` | `/__tests__/index.test${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/app${'/(landing)'}/layout` | `/../../web/app/layout`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/landing/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/landing/hero`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/landing/features`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/landing/stats`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/landing/final-cta`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/landing/footer`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/layouts/header/app-header`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/index.test`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
